name: "Bug Report"
description: "File a bug report to help us improve"
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: input
    id: "bob_version"
    validations:
      required: true
    attributes:
      label: "Bob Version"
      description: "Run `bob --version` and paste the output here."
      placeholder: "ex: bob 4.1.0"
  - type: "input"
    id: "rust_version"
    validations:
      required: false
    attributes:
      label: "Rust Version"
      description: "Run `rustc --version` and paste the output here. (Optional if you're not building `bob` from source.)"
      placeholder: "ex: rustc 1.94.0-nightly (37aa2135b 2025-12-08)"
  # - type: input
  #   id: "os_arch"
  #   validations:
  #     required: true
  #   attributes:
  #     label: "Operating System and Architecture"
  #     description: "Please provide your OS and architecture. (You can find this by running `uname -a` on Linux/macOS or `systeminfo` on Windows.)"
  #     placeholder: "ex: Ubuntu 22.04, x86_64"
  ## Alternative: use dropdowns for OS and architecture (uncomment and replace the input above if preferred)
  - type: dropdown
    id: "os"
    validations:
      required: true
    attributes:
      label: "Operating System"
      description: "Please select your operating system."
      options:
        - Windows
        - Linux
        - macOS
        - Other (mention in description)
  - type: input
    id: "distro"
    validations:
      required: false
    attributes:
      label: "Linux Distribution (if applicable)"
      description: |
        If you selected Linux above, please specify your distribution
        You can get this by running either `lsb_release -a`, `cat /etc/os-release`, or `uname -a`.
        (e.g., Ubuntu 22.04, Fedora 38).
      placeholder: "ex: Ubuntu 22.04"
      value: "N/A"
  - type: dropdown
    id: "arch"
    validations:
      required: true
    attributes:
      label: "Architecture"
      description: "Please select your system architecture."
      options:
        - x86_64
        - aarch64
        - Other (mention in description)
  - type: textarea
    id: "description"
    validations:
      required: true
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "ex: When I do [...], I expect [...] but instead [...]."
  - type: textarea
    id: "expected_behavior"
    validations:
      required: true
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "ex: The expected behavior was [...]"
  - type: textarea
    id: "actual_behavior"
    validations:
      required: true
    attributes:
      label: "Actual Behavior"
      description: "A clear and concise description of what happened instead."
      placeholder: "ex: The actual behavior was [...]"
  - type: textarea
    id: "steps"
    validations:
      required: true
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Run the command '....'
        3. Wait for '....'
        4. See error
      value: "1. \n2. \n3. \n4. \n"
  - type: textarea
    id: "logs"
    validations:
      required: false
    attributes:
      label: "Logs/Errors"
      description: |
        Please provide any relevant logs or error messages.
        For long logs, wrap them in a collapsible section using Markdown:
        ```
        <details>
          <summary>
            Click to expand logs
          </summary>
        Paste your log here
        </details>
        ```
      placeholder: "Paste logs or errors here, using the collapsible format if lengthy."
      value: "The error that occurred was:\n\n```\n\n```"
  - type: textarea
    id: "config"
    validations:
      required: false
    attributes:
      label: "Config File (if relevant)"
      description: |
        If relevant, please paste the contents of your config file.
        The default location is `~/.config/bob/config.json`.
      placeholder: "Paste config here (if relevant)."
      value: "{\n  \n}"
      render: json
