# Using neosh' ci https://github.com/neo-sh/neosh/blob/main/.github/workflows/format.yml
name: Format
on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - uses: Swatinem/rust-cache@v1
      - name: Run make rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: rustfmt

      - name: Commit formatted source files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Bob Format
          default_author: github_actions
          message: "refactor: formatted code"
          push: true